-- Lock Database
UPDATE public.databasechangeloglock SET LOCKED = TRUE, LOCKEDBY = 'DESKTOP (255.254.126.243)', LOCKGRANTED = '2021-11-13 23:15:42.197' WHERE ID = 1 AND LOCKED = FALSE;

CREATE TABLE IF NOT EXISTS public.company (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                          date_from TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
                                          date_to TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
                                          name VARCHAR(512),
                                          address VARCHAR(512),
                                          CONSTRAINT "companyPK" PRIMARY KEY (id));

-- Release Database Lock
UPDATE public.databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;